// <auto-generated />
namespace Perchero.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class varaible_punho_jeje : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(varaible_punho_jeje));
        
        string IMigrationMetadata.Id
        {
            get { return "201706282203461_varaible_punho_jeje"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
