// <auto-generated />
namespace Perchero.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Estado_terminado_en_pedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Estado_terminado_en_pedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201706132340582_Estado_terminado_en_pedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
